export const projects = [
  {
    id: "1",
    screenshot: "/Flic Movies.png",
    title: "Flic Movies",
    subTitle: "Modern enterprise-grade streaming web application",
    stack: [
      "next.js",
      "NestJS",
      "tailwindcss",
      "Prisma ORM",
      "PostgreSQL",
      "React Query"
    ],
    description: `Flic Movies is a modern, enterprise-grade streaming web application built as a monorepo. It features a highly optimized Next.js frontend for dynamic SEO and user interfaces, paired with a robust, heavily-secured NestJS backend for handling user authentication, comments, and watchlists.`,
    date: "2026",
    github: "https://github.com/fredymorara",
    live: "https://flicmovies.me",
    color: "#e50914",
    btnBg: "rgba(229,9,20,0.5)",
    btnBgHover: "rgba(229,9,20,0.8)",
    cardBg: "rgba(229,9,20,0.05)",
  },
  {
    id: "2",
    screenshot: "/Kumo Anime.png",
    title: "Kumo Anime",
    subTitle: "Premium anime streaming and discovery platform",
    stack: [
      "SolidStart",
      "tailwindcss",
      "Motion One",
      "Bun",
      "GraphQL"
    ],
    description: `A premium, blazing-fast anime streaming and discovery platform built from the ground up for absolute peak performance and a stunning cinematic user experience. Built with SolidStart, Tailwind CSS v4, and AniList GraphQL API, it features streaming SSR, a cinematic UI/UX, advanced episode selection, local watch history, and real-time TV release schedules.`,
    date: "2026",
    github: "https://github.com/fredymorara",
    live: "https://anime.flicmovies.me",
    color: "#8b5cf6",
    btnBg: "rgba(139,92,246,0.5)",
    btnBgHover: "rgba(139,92,246,0.8)",
    cardBg: "rgba(139,92,246,0.05)",
  },
  {
    id: "3",
    screenshot: "/Hans Credit.png",
    title: "HansCredit",
    subTitle: "A Credit loans application.",
    stack: [
      "next.js",
      "JavaScript",
      "nodemailer",
      "tailwindcss",
      "Framer Motion",
      "pnpm",
    ],
    description: `HansCredit is a modern credit loans application designed for users to apply for and manage credit loans. Built with Next.js, JavaScript, and Tailwind CSS, it offers a seamless user experience with features like loan applications, status tracking, and secure communication via nodemailer. The platform includes a responsive UI with animations powered by Framer Motion and is optimized using pnpm for fast builds.`,
    date: "Feb 10, 2026",
    github: "https://github.com/fredymorara/HansCredit",
    live: "https://hanscredit.co.ke/",
    color: "#ecb613",
    btnBg: "#ecb613",
    btnBgHover: "#ecb613",
    cardBg: "rgba(154,52,18,0.05)",
  },
  {
    id: "4",
    screenshot: "/Mpira Streams.png",
    title: "Mpira Streams",
    subTitle: "Sports streaming application",
    stack: [
      "react",
      "Redux",
      "JavaScript",
      "tailwindcss",
      "REST API",
    ],
    description: `A Front-end React application to consume a public sports streaming API. It focuses on a modular structure, state management with Redux, and reusable components while keeping the app lightweight and easy to understand.`,
    date: "2025",
    github: "https://github.com/fredymorara",
    live: "https://sports.flicmovies.me",
    color: "#ffffff",
    btnBg: "rgba(220,36,118,0.5)",
    btnBgHover: "rgba(220,36,118,0.8)",
    cardBg: "rgba(255,81,47,0.05)",
  },
  {
    id: "5",
    screenshot: "/Smart AI Library Assistant.png",
    title: "Smart AI Library Assistant",
    subTitle: "AI-powered library assistant",
    stack: [
      "react",
      "R.A.G Pipeline",
      "Vector Databases",
      "Hugging Face API",
      "Groq",
      "next.js",
      "JavaScript",
      "tailwindcss",
      "shadcn",
      "Clerk Authentication",
      "Supabase",
    ],
    description:
      "The Smart AI Library Assistant is an innovative application designed to enhance the library experience using AI technology. It utilizes a Retrieval-Augmented Generation (R.A.G) pipeline to provide users with accurate and relevant information about library resources. The assistant integrates with vector databases to efficiently retrieve data and leverages the Hugging Face API for natural language processing capabilities. Built with React and Next.js, it features a user-friendly interface styled with Tailwind CSS and ShadCN components. User authentication is handled through Clerk, while Supabase manages the backend services, ensuring a seamless and secure user experience.",
    date: "Dec 19, 2025",
    github: "https://github.com/fredymorara/ai-library",
    live: "https://ai-library-update.vercel.app/",
    color: "#39e75f",
    btnBg: "#39e75f",
    btnBgHover: "#39e75f",
    cardBg: "rgba(91,33,182,0.05)",
  },
  {
    id: "6",
    screenshot: "/AI Spam Message Detector.png",
    title: "AI Spam Message Detector",
    subTitle: "AI-powered spam message detection tool",
    stack: [
      "Streamlit",
      "Pandas",
      "Numpy",
      "scikit-learn",
      "Python",
      "Linear SVM",
      "Natural Language Processing",
      "Machine Learning",
      "nltk",
    ],
    description: `The AI Spam Message Detector is a cutting-edge application that leverages artificial intelligence to identify and filter out spam messages. This application uses a Linear Support Vector Machine (SVM) model to classify text messages as either "Spam" or "Ham" (legitimate). It was developed as part of an AI mini-project.

`,
    date: "Jul 20, 2025",
    github: "https://github.com/fredymorara/AI-Spam-Detector-App",
    live: "https://aispamdetector.streamlit.app/",
    color: "#ADD8E6",
    btnBg: "#ADD8E6",
    btnBgHover: "#ADD8F9",
    cardBg: "rgba(22,101,52,0.05)",
  },
  {
    id: "7",
    screenshot: "/Student Welfare Management System.png",
    title: "Student Welfare Management System",
    subTitle: "Student welfare management app",
    stack: [
      "react",
      "JavaScript",
      "Node.js",
      "Mpesa Daraja api",
      "express",
      "mongodb",
      "tailwindcss",
      "mongoose",
      "JWT",
    ],
    description:
      "The Student Welfare Management System is a comprehensive application designed to manage student welfare activities and resources. Built with React for the frontend and Node.js with Express for the backend, it utilizes MongoDB for data storage and Mongoose for object modeling. The system features user authentication with JWT, allowing students to access resources, submit requests, and track their welfare activities efficiently.",
    date: "Sep 20, 2025",
    github: "https://github.com/fredymorara/wms",
    live: "https://kabarakstudentwelfare.netlify.app/",
    color: "#800000",
    btnBg: "#800000",
    btnBgHover: "#800000",
    cardBg: "rgba(55,48,163,0.05)",
  },
];
