export const projects = [
  {
    id: "1",
    screenshot: "/Hans Credit.png",
    title: "HansCredit",
    subTitle: "A Credit loans application.",
    stack: [
      "next.js",
      "JavaScript",
      "nodemailer",
      "tailwindcss",
      "Framer Motion",
      "pnpm",
    ],
    description: `HansCredit is a modern credit loans application designed for users to apply for and manage credit loans. Built with Next.js, JavaScript, and Tailwind CSS, it offers a seamless user experience with features like loan applications, status tracking, and secure communication via nodemailer. The platform includes a responsive UI with animations powered by Framer Motion and is optimized using pnpm for fast builds.`,
    date: "Feb 10, 2026",
    github: "https://github.com/fredymorara/HansCredit",
    live: "https://hanscredit.co.ke/",
    color: "#ecb613",
    btnBg: "#ecb613",
    btnBgHover: "#ecb613",
    cardBg: "rgba(154,52,18,0.05)",
  },
  {
    id: '2',
    screenshot: '/Smart AI Library Assistant.png',
    title: 'Smart AI Library Assistant',
    subTitle: 'AI-powered library assistant',
    stack: [
      'react',
      'R.A.G Pipeline',
      'Vector Databases',
      'Hugging Face API',
      'Groq',
      'next.js',
      'JavaScript',
      'tailwindcss',
      'shadcn',
      'Clerk Authentication',
      'Supabase'
    ],
    description:
      'The Smart AI Library Assistant is an innovative application designed to enhance the library experience using AI technology. It utilizes a Retrieval-Augmented Generation (R.A.G) pipeline to provide users with accurate and relevant information about library resources. The assistant integrates with vector databases to efficiently retrieve data and leverages the Hugging Face API for natural language processing capabilities. Built with React and Next.js, it features a user-friendly interface styled with Tailwind CSS and ShadCN components. User authentication is handled through Clerk, while Supabase manages the backend services, ensuring a seamless and secure user experience.',
    date: 'Dec 19, 2025',
    github: 'https://github.com/fredymorara/ai-library',
    live: 'https://ai-library-update.vercel.app/',
    color: '#39e75f',
    btnBg: '#39e75f',
    btnBgHover: '#39e75f',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: "3",
    screenshot: "/Student Welfare Management System.png",
    title: "Student Welfare Management System",
    subTitle: "Student welfare management app",
    stack: [
      "react",
      "JavaScript",
      "Node.js",
      "Mpesa Daraja api",
      "express",
      "mongodb",
      "tailwindcss",
      "mongoose",
      "JWT",
    ],
    description:
      "The Student Welfare Management System is a comprehensive application designed to manage student welfare activities and resources. Built with React for the frontend and Node.js with Express for the backend, it utilizes MongoDB for data storage and Mongoose for object modeling. The system features user authentication with JWT, allowing students to access resources, submit requests, and track their welfare activities efficiently.",
    date: "Sep 20, 2025",
    github: "https://github.com/fredymorara/wms",
    live: "https://kabarakstudentwelfare.netlify.app/",
    color: "#800000",
    btnBg: "#800000",
    btnBgHover: "#800000",
    cardBg: "rgba(55,48,163,0.05)",
  },
  {
    id: '4',
    screenshot: '/AI Spam Message Detector.png',
    title: 'AI Spam Message Detector',
    subTitle: 'AI-powered spam message detection tool',
    stack: ['Streamlit', 'Pandas', 'Numpy', 'scikit-learn', 'Python', 'Linear SVM', 'Natural Language Processing', 'Machine Learning','nltk'],
    description: `The AI Spam Message Detector is a cutting-edge application that leverages artificial intelligence to identify and filter out spam messages. This application uses a Linear Support Vector Machine (SVM) model to classify text messages as either "Spam" or "Ham" (legitimate). It was developed as part of an AI mini-project.

`,
    date: 'Jul 20, 2025',
    github: 'https://github.com/fredymorara/AI-Spam-Detector-App',
    live: 'https:///aispamdetector.streamlit.app/',
    color: '#ADD8E6',
    btnBg: '#ADD8E6',
    btnBgHover: '#ADD8F9',
    cardBg: 'rgba(22,101,52,0.05)',
  },
  /*{
    id: '5',
    screenshot: '/chatbotify.png',
    title: 'ChatBotify Gallery',
    subTitle: 'ChatBotify Gallery website',
    stack: ['react', 'tailwindcss', 'figma'],
    description: `Chatbotify Gallery is an (open-source) project showcasing customizable chatbot designs. When I joined the team, one major blocker was the lack of a unified color palette and design system. I addressed this by creating a cohesive palette that aligned with the application's style and feel, streamlining the design process for the entire team. My contributions include designing and developing the About page using React and Tailwind CSS, as well as working on the Theme Builder page—a feature enabling users to customize chatbots to match their tone and branding.`,
    date: 'Jan 2, 2024',
    github: 'https://github.com/adel-gu/react-chatbotify-gallery-website',
    live: 'https://gallery.react-chatbotify.com/',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
  },*/
];
